jwt-config:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-token-lifecycle: ${JWT_TOKEN_LIFECYCLE}

server:
  port: ${VIDEO_SERVICE_PORT}

spring:
  application:
    name: video-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${VIDEO_SERVICE_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

remote-configuration:
  statistics-url: http://localhost:${STATISTICS_PORT}
  storage-service-url: http://localhost:${STORAGE_SERVICE_PORT}