application:
  jwt-secret-key: ${JWT_SECRET_KEY}
  jwt-token-lifecycle: ${JWT_TOKEN_LIFECYCLE}

spring:
  application:
    name: video-service

  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${DB_NAME}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB